name: CI

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*' # Push events to any matching semantic tag. For example, 1.10.1 or 2.0.0 or 3.0.0-alpha.

jobs:
  build:
    runs-on: self-hosted
    container: 
      image: archlinux:latest
      options: --privileged

    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: |
        pacman --noconfirm -Suy
        pacman --disable-download-timeout --noconfirm -S zip
        ./build.sh
        zip -9 EFASpi5.zip -s 1900m EFASpi5.img
        echo "Fixup directory permissions"
        tgt=$(ls -an | tr -s ' ' | cut -d ' ' -f3-4 | head -n2 | tr -d '\n' | tr ' ' ':')
        chown -R ${tgt} ./*
        chown -R ${tgt} ./.*

    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: EFASpi5
        path: |
          EFASpi5.z*

    - name: Cleanup
      run: |
        rm -f EFASpi5.img

  create_release:
    name: Create release
    runs-on: self-hosted
    needs: build
    permissions:
      contents: write
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - uses: actions/checkout@v3

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          prerelease: false
          draft: false
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          files: EFASpi5.z*